const actionTypes = {
  SELECT_FROM_CHAIN: 'SELECT_FROM_CHAIN',
  SELECT_TO_CHAIN: 'SELECT_TO_CHAIN',

  SELECT_FROM_ACCOUNT: 'SELECT_FROM_ACCOUNT',
  SELECT_TO_ACCOUNT: 'SELECT_TO_ACCOUNT',

  SELECT_NFT: 'SELECT_NFT',
  SELECT_COIN: 'SELECT_COIN',
  SWAP_CHAINS: 'SWAP_CHAINS',

  TRANSFER_COINS: 'TRANSFER_COINS',
  TRANSFER_NFT: 'TRANSFER_NFT',

  CHANGE_AMMOUNT: 'CHANGE_AMMOUNT',
  GET_BALANCE: 'GETBALANCE',
  GET_BALANCES: 'GETBALANCES',

  LIST_NFTS: 'LIST_NFTS',

  NFT_LOADING: 'NFT_LOADING',

  SHOW_LOADER: 'SHOW_LOADER',

  SHOW_MODAL: 'SHOW_MODAL',
}

export default actionTypes
